export enum ActionType {
    LOGIN_SUCCESS = 'LOGIN_SUCCESS',
    LOGIN_FAIL = 'LOGIN_FAIL',
    LOGOUT = 'LOGOUT',

    USER_LOADED = 'USER_LOADED',
    AUTH_ERROR = 'AUTH_ERROR',

    REGISTER_SUCCESS = 'REGISTER_SUCCESS',
    REGISTER_FAIL = 'REGISTER_FAIL',

    SET_ALERT = 'SET_ALERT',
    REMOVE_ALERT = 'REMOVE_ALERT'
}